require: rubocop-rspec
inherit_from: .rubocop_todo.yml

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false

Layout/LineLength:
  Max: 100
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false

Naming/FileName:
  Exclude:
    - 'lib/grpc-web.rb'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - given
    - which
    - before
    - after
    - because
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExampleLength:
  Max: 10