require: rubocop-rspec
inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'spec/pb-ruby/goodbye_pb.rb'
    - vendor/bundle/**/*

Style/TrailingCommaInArguments:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  Enabled: true
  EnforcedStyleForMultiline: consistent_comma
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  AutoCorrect: true
Style/GuardClause:
  MinBodyLength: 4

Layout/LineLength:
  Max: 100
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Metrics/MethodLength:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/CyclomaticComplexity:
  Max: 13
Metrics/PerceivedComplexity:
  Max: 13

Naming/FileName:
  Exclude:
    - 'lib/grpc-web.rb'

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - given
    - which
    - before
    - after
    - because
    - and
RSpec/MultipleExpectations:
  Max: 2
RSpec/ExampleLength:
  Max: 15
RSpec/NestedGroups:
  Max: 5
RSpec/FilePath:
  Enabled: false
