name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Install Docker and Docker Compose
        run: |
          # Remove conflicting containerd package if it exists
          sudo apt-get remove -y containerd
          sudo apt-get update
          sudo apt-get install -y docker.io docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Run Rake tasks
        run: rake
