name: Test Suite

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Ruby 2.7
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
        run: gem install bundler -v 2.4.22 && bundle install

      - name: Install Docker and Docker Compose
        run: |
          # Install Docker using the official convenience script
          curl -fsSL https://get.docker.com -o get-docker.sh
          sh get-docker.sh
          sudo apt-get install -y docker-compose

      - name: Build Docker image
        run: docker-compose build

      - name: Run Rake tasks
        run: rake
